[theme]
inherit = pydata_sphinx_theme
stylesheet = styles/quantecon-sphinx-theme.css

[options]
# --- Layout ---
content_max_width = 48rem
toc_sticky = True
toc_autoexpand = True
toc_collapsible = True

# --- Appearance ---
color_scheme = default
dark_mode = auto
dark_logo =
google_fonts = True
custom_css =

# --- Code ---
code_style = theme

# --- Scientific ---
mathjax_macros = True

# --- Navigation ---
show_nav_level = 1
persistent_sidebar = False

# --- Content ---
show_last_modified = False
show_page_toc_title = True

# --- Repository ---
repository_url =
repository_branch = main
path_to_docs =
use_repository_button = False
use_edit_page_button = False
use_issues_button = False

# --- SEO ---
description =
keywords =
og_image =
twitter_handle =

# --- Footer ---
extra_footer =
